# Generated by Django 4.2.6 on 2023-11-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='tg id'),
        ),
    ]
