# Generated by Django 4.2.6 on 2023-11-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_sending',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней отправки'),
        ),
    ]
